baseURL: "https://sgp2021.github.io/"
languageCode: en-us
title: SGP 2022 - Symposium on Geometry Processing 2022
theme: minimalConference
languages:
  en:
    languageName: English
    weight: 1
    about: "The Symposium on Geometry Processing (SGP) is the premier venue for
    disseminating new research ideas and cutting-edge results in geometry
    processing. In this research area, concepts from mathematics, computer science,
    and engineering are studied and applied to offer new insights and design
    efficient algorithms for acquisition, modeling, analysis, manipulation,
    simulation and other types of processing of 3D models and shape collections."
    sponsorPlea: "if you like to become a sponsor SGP 2022."
    submitNow: "Begin your submision now."
menu:
  main:
    - name: submit
      url: /submit/
      weight: 10
    - name: program
      url: /program/
      weight: 20
    - name: organization
      url: /organization/
      weight: 30
    - name: awards
      url: /awards/
      weight: 40
    - name: previous_sgps
      url: /past/
      weight: 50
Params:
  submissionUrl: "https://srmv2.eg.org/COMFy/Conference/SGP_2022"
  events: 
    - id: "graduate_school"
      date: "July 2-3, 2022"
    - id: "conference"
      date: "July 4-6, 2022"
  importantDates:
    - id: paper_submission
      date: "April 11, 2022, 23:59 UTC"
    - id: notification_of_acceptance
      date: "May 10, 2022"
    - id: revised_version_due
      date: "June 10, 2022, 23:59 UTC"
    - id: camera_ready_due
      date: "June 20, 2022, 23:59 UTC"
    - id: graduate_school
      date: "July 2-3, 2022"
    - id: conference
      date: "July 4–6, 2022"
  chairs:
#  - id: conference_co_chairs
#    items: 
#      - name: "Name Name"
#        email: "example@example.edu"
#        affiliation: "University of Example"
  - id: technical_program_co_chairs
    items: 
      - name: "Marcel Campen"
        email: ""
        affiliation: "(Osnabrück University)"
      - name: "Michela Spagnuolo"
        email: ""
        affiliation: "(CNR)"
  - id: graduate_school_co_chairs
    items: 
      - name: "Ruizhen Hu"
        email: ""
        affiliation: "(Shenzhen University)"
      - name: "Teseo Schneider"
        email: ""
        affiliation: "(University of Victoria)"

  - id: awards_chair
    items: 
      - name: "Marc Alexa"
        email: "firstname.lastname at tu-berlin.de"
        affiliation: "Technische Universität Berlin"
  committees:
    - id: technical_papers_committee
      members:
        - name: Name Name
          affiliation: affiliation
          country: "Austria"
    - id: awards_committee
      members:
        - name: Name Name
          affiliation: affiliation
          country: "Austria"
    - id: steering_committee
      members: 
        - name: "Leif Kobbelt"
          affiliation: "RWTH Aachen University"
          country: "Germany"
        - name: "Marc Alexa"
          affiliation: "TU Berlin"
          country: "Germany"
        - name: "Pierre Alliez"
          affiliation: "INRIA"
          country: "France"
        - name: "Mirela Ben-Chen"
          affiliation: "Technion-IIT"
          country: "Israel"
        - name: "Hui Huang"
          affiliation: "Shenzhen University"
          country: "China"
        - name: "Niloy Mitra"
          affiliation: "University College London"
          country: "UK"
        - name: "Daniele Panozzo"
          affiliation: "New York University"
          country: "USA"
    - id: student_volunteers
      members:
        - name: Name Name
          affiliation: affiliation
          country: Canada
  flagEmojis:
    Afghanistan: "🇦🇫"
    Albania: "🇦🇱"
    Algeria: "🇩🇿"
    American Samoa: "🇦🇸"
    Andorra: "🇦🇩"
    Angola: "🇦🇴"
    Anguilla: "🇦🇮"
    Antarctica: "🇦🇶"
    Antigua and Barbuda: "🇦🇬"
    Argentina: "🇦🇷"
    Armenia: "🇦🇲"
    Aruba: "🇦🇼"
    Australia: "🇦🇺"
    Austria: "🇦🇹"
    Azerbaijan: "🇦🇿"
    Bahamas: "🇧🇸"
    Bahrain: "🇧🇭"
    Bangladesh: "🇧🇩"
    Barbados: "🇧🇧"
    Belarus: "🇧🇾"
    Belgium: "🇧🇪"
    Belize: "🇧🇿"
    Benin: "🇧🇯"
    Bermuda: "🇧🇲"
    Bhutan: "🇧🇹"
    Bolivia: "🇧🇴"
    Bonaire, Sint Eustatius and Saba: "🇧🇶"
    Bosnia and Herzegovina: "🇧🇦"
    Botswana: "🇧🇼"
    Bouvet Island: "🇧🇻"
    Brazil: "🇧🇷"
    British Indian Ocean Territory: "🇮🇴"
    Brunei Darussalam: "🇧🇳"
    Bulgaria: "🇧🇬"
    Burkina Faso: "🇧🇫"
    Burundi: "🇧🇮"
    Cambodia: "🇰🇭"
    Cameroon: "🇨🇲"
    Canada: "🇨🇦"
    Cape Verde: "🇨🇻"
    Cayman Islands: "🇰🇾"
    Central African Republic: "🇨🇫"
    Chad: "🇹🇩"
    Chile: "🇨🇱"
    China: "🇨🇳"
    Christmas Island: "🇨🇽"
    Cocos (Keeling) Islands: "🇨🇨"
    Colombia: "🇨🇴"
    Comoros: "🇰🇲"
    Congo: "🇨🇩"
    Congo: "🇨🇬"
    Cook Islands: "🇨🇰"
    Costa Rica: "🇨🇷"
    Croatia: "🇭🇷"
    Cuba: "🇨🇺"
    Curaçao: "🇨🇼"
    Cyprus: "🇨🇾"
    Czech Republic: "🇨🇿"
    Côte D'Ivoire: "🇨🇮"
    Denmark: "🇩🇰"
    Djibouti: "🇩🇯"
    Dominica: "🇩🇲"
    Dominican Republic: "🇩🇴"
    Ecuador: "🇪🇨"
    Egypt: "🇪🇬"
    El Salvador: "🇸🇻"
    Equatorial Guinea: "🇬🇶"
    Eritrea: "🇪🇷"
    Estonia: "🇪🇪"
    Ethiopia: "🇪🇹"
    Falkland Islands (Malvinas): "🇫🇰"
    Faroe Islands: "🇫🇴"
    Fiji: "🇫🇯"
    Finland: "🇫🇮"
    France: "🇫🇷"
    French Guiana: "🇬🇫"
    French Polynesia: "🇵🇫"
    French Southern Territories: "🇹🇫"
    Gabon: "🇬🇦"
    Gambia: "🇬🇲"
    Georgia: "🇬🇪"
    Germany: "🇩🇪"
    Ghana: "🇬🇭"
    Gibraltar: "🇬🇮"
    Greece: "🇬🇷"
    Greenland: "🇬🇱"
    Grenada: "🇬🇩"
    Guadeloupe: "🇬🇵"
    Guam: "🇬🇺"
    Guatemala: "🇬🇹"
    Guernsey: "🇬🇬"
    Guinea-Bissau: "🇬🇼"
    Guinea: "🇬🇳"
    Guyana: "🇬🇾"
    Haiti: "🇭🇹"
    Heard Island and Mcdonald Islands: "🇭🇲"
    Honduras: "🇭🇳"
    Hong Kong: "🇭🇰"
    Hungary: "🇭🇺"
    Iceland: "🇮🇸"
    India: "🇮🇳"
    Indonesia: "🇮🇩"
    Iran: "🇮🇷"
    Iraq: "🇮🇶"
    Ireland: "🇮🇪"
    Isle of Man: "🇮🇲"
    Israel: "🇮🇱"
    Italy: "🇮🇹"
    Jamaica: "🇯🇲"
    Japan: "🇯🇵"
    Jersey: "🇯🇪"
    Jordan: "🇯🇴"
    Kazakhstan: "🇰🇿"
    Kenya: "🇰🇪"
    Kiribati: "🇰🇮"
    Kuwait: "🇰🇼"
    Kyrgyzstan: "🇰🇬"
    Lao People's Democratic Republic: "🇱🇦"
    Latvia: "🇱🇻"
    Lebanon: "🇱🇧"
    Lesotho: "🇱🇸"
    Liberia: "🇱🇷"
    Libya: "🇱🇾"
    Liechtenstein: "🇱🇮"
    Lithuania: "🇱🇹"
    Luxembourg: "🇱🇺"
    Macao: "🇲🇴"
    Macedonia: "🇲🇰"
    Madagascar: "🇲🇬"
    Malawi: "🇲🇼"
    Malaysia: "🇲🇾"
    Maldives: "🇲🇻"
    Mali: "🇲🇱"
    Malta: "🇲🇹"
    Marshall Islands: "🇲🇭"
    Martinique: "🇲🇶"
    Mauritania: "🇲🇷"
    Mauritius: "🇲🇺"
    Mayotte: "🇾🇹"
    Mexico: "🇲🇽"
    Micronesia: "🇫🇲"
    Moldova: "🇲🇩"
    Monaco: "🇲🇨"
    Mongolia: "🇲🇳"
    Montenegro: "🇲🇪"
    Montserrat: "🇲🇸"
    Morocco: "🇲🇦"
    Mozambique: "🇲🇿"
    Myanmar: "🇲🇲"
    Namibia: "🇳🇦"
    Nauru: "🇳🇷"
    Nepal: "🇳🇵"
    The Netherlands: "🇳🇱"
    New Caledonia: "🇳🇨"
    New Zealand: "🇳🇿"
    Nicaragua: "🇳🇮"
    Niger: "🇳🇪"
    Nigeria: "🇳🇬"
    Niue: "🇳🇺"
    Norfolk Island: "🇳🇫"
    North Korea: "🇰🇵"
    Northern Mariana Islands: "🇲🇵"
    Norway: "🇳🇴"
    Oman: "🇴🇲"
    Pakistan: "🇵🇰"
    Palau: "🇵🇼"
    Palestinian Territory: "🇵🇸"
    Panama: "🇵🇦"
    Papua New Guinea: "🇵🇬"
    Paraguay: "🇵🇾"
    Peru: "🇵🇪"
    Philippines: "🇵🇭"
    Pitcairn: "🇵🇳"
    Poland: "🇵🇱"
    Portugal: "🇵🇹"
    Puerto Rico: "🇵🇷"
    Qatar: "🇶🇦"
    Romania: "🇷🇴"
    Russia: "🇷🇺"
    Rwanda: "🇷🇼"
    Réunion: "🇷🇪"
    Saint Barthélemy: "🇧🇱"
    Saint Helena, Ascension and Tristan Da Cunha: "🇸🇭"
    Saint Kitts and Nevis: "🇰🇳"
    Saint Lucia: "🇱🇨"
    Saint Martin (French Part): "🇲🇫"
    Saint Pierre and Miquelon: "🇵🇲"
    Saint Vincent and The Grenadines: "🇻🇨"
    Samoa: "🇼🇸"
    San Marino: "🇸🇲"
    Sao Tome and Principe: "🇸🇹"
    Saudi Arabia: "🇸🇦"
    Senegal: "🇸🇳"
    Serbia: "🇷🇸"
    Seychelles: "🇸🇨"
    Sierra Leone: "🇸🇱"
    Singapore: "🇸🇬"
    Sint Maarten (Dutch Part): "🇸🇽"
    Slovakia: "🇸🇰"
    Slovenia: "🇸🇮"
    Solomon Islands: "🇸🇧"
    Somalia: "🇸🇴"
    South Africa: "🇿🇦"
    South Georgia: "🇬🇸"
    South Korea: "🇰🇷"
    South Sudan: "🇸🇸"
    Spain: "🇪🇸"
    Sri Lanka: "🇱🇰"
    Sudan: "🇸🇩"
    Suriname: "🇸🇷"
    Svalbard and Jan Mayen: "🇸🇯"
    Swaziland: "🇸🇿"
    Sweden: "🇸🇪"
    Switzerland: "🇨🇭"
    Syrian Arab Republic: "🇸🇾"
    Taiwan: "🇹🇼"
    Tajikistan: "🇹🇯"
    Tanzania: "🇹🇿"
    Thailand: "🇹🇭"
    Timor-Leste: "🇹🇱"
    Togo: "🇹🇬"
    Tokelau: "🇹🇰"
    Tonga: "🇹🇴"
    Trinidad and Tobago: "🇹🇹"
    Tunisia: "🇹🇳"
    Turkey: "🇹🇷"
    Turkmenistan: "🇹🇲"
    Turks and Caicos Islands: "🇹🇨"
    Tuvalu: "🇹🇻"
    Uganda: "🇺🇬"
    Ukraine: "🇺🇦"
    United Arab Emirates: "🇦🇪"
    UK: "🇬🇧"
    United States Minor Outlying Islands: "🇺🇲"
    USA: "🇺🇸"
    Uruguay: "🇺🇾"
    Uzbekistan: "🇺🇿"
    Vanuatu: "🇻🇺"
    Vatican City: "🇻🇦"
    Venezuela: "🇻🇪"
    Viet Nam: "🇻🇳"
    Virgin Islands, British: "🇻🇬"
    Virgin Islands, U.S.: "🇻🇮"
    Wallis and Futuna: "🇼🇫"
    Western Sahara: "🇪🇭"
    Yemen: "🇾🇪"
    Zambia: "🇿🇲"
    Zimbabwe: "🇿🇼"
    Åland Islands: "🇦🇽"
  pastEvents:
    - year: "2021"
      url: "https://sgp2021.github.io/"
      city: "Remote (Toronto)"
      country: "Canada"
      date: "July 12-14"
    - year: "2020"
      url: "https://sgp2020.sites.uu.nl/"
      city: "Utrecht"
      country: "The Netherlands"
      date: "July 6-8"
    - year: "2019"
      url: "https://sgp2019.di.unimi.it/index.html"
      city: "Milan"
      country: "Italy"
      date: "July 8-10"
    - year: "2018"
      url: "https://sgp2018.sciencesconf.org/"
      city: "Paris"
      country: "France"
      date: "July 7-11"
    - year: "2017"
      url: "https://web.archive.org/web/20210413233643/http://geometry.cs.ucl.ac.uk/SGP2017/"
      city: "London"
      country: "UK"
      date: "July 1-5"
    - year: "2016"
      url: "http://igs2016.mi.fu-berlin.de/sgp2016/"
      city: "Berlin"
      country: "Germany"
      date: "June 20-24"
    - year: "2015"
      url: "http://www.geometrie.tugraz.at/sgp2015/"
      city: "Graz"
      country: "Austria"
      date: "July 6-8"
    - year: "2014"
      url: "http://www.cs.cf.ac.uk/sgp2014/"
      city: "Cardiff"
      country: "UK"
      date: "July 9-11"
    - year: "2013"
      url: "https://web.archive.org/web/20200629093239/http://sgp.ge.imati.cnr.it/"
      city: "Genova"
      country: "Italy"
      date: "July 3-5"
    - year: "2012"
      url: "http://www.ioc.ee/sgp12/index.php"
      city: "Tallinn"
      country: "Estonia"
      date: "July 16-18"
    - year: "2011"
      url: "http://sgp2011-lgg.epfl.ch/Home.html"
      city: "Lausanne"
      country: "Switzerland"
      date: "July 20-22"
    - year: "2010"
      url: "http://sgp2010.liris.cnrs.fr/index.php"
      city: "Lyon"
      country: "France"
      date: "July 5-7"
    - year: "2009"
      url: "http://sgp09.mi.fu-berlin.de/index.html"
      city: "Berlin"
      country: "Germany"
      date: "July 15-17"
    - year: "2008"
      url: "http://www2.imm.dtu.dk/SGP08/"
      city: "Copenhagen"
      country: "Denmark"
      date: "July 2-4"
    - year: "2007"
      url: "http://www.lsi.upc.edu/~alvar/SGP07/"
      city: "Barcelona"
      country: "Spain"
      date: "July 4-6"
    - year: "2006"
      url: "https://web.archive.org/web/20161007164420/http://sgp2006.sc.unica.it/"
      city: "Cagliari"
      country: "Italy"
      date: "June 26-28"
    - year: "2005"
      url: "http://www.cg.tuwien.ac.at/events/SGP05/index.html"
      city: "Vienna"
      country: "Austria"
      date: "July 4-6"
    - year: "2004"
      url: "http://www-sop.inria.fr/geometrica/events/sgp2004/index.html"
      city: "Nice"
      country: "France"
      date: "July 8-10"
    - year: "2003"
      url: "http://www-i8.informatik.rwth-aachen.de/SGP/index.html"
      city: "Aachen"
      country: "Germany"
      date: "June 23-25"
